[target.mipsel-unknown-linux-gnu]
linker = "mipsel-linux-gnu-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-gnu-gcc"

[env]
CC_mipsel_unknown_linux_gnu = "mipsel-linux-gnu-gcc"
CXX_mipsel_unknown_linux_gnu = "mipsel-linux-gnu-g++"
AR_mipsel_unknown_linux_gnu = "mipsel-linux-gnu-ar" 