version: '3.8'

services:
  rust-mips:
    build:
      context: .         # 当前目录，确保这里有 Dockerfile
      dockerfile: Dockerfile
    network_mode: host
    container_name: rust-mipsel-dev
    volumes:
      - ${VOLUME_PATH}/rust-mipsel-data:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true